services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: reserveit_db
    environment:
      POSTGRES_DB: reserveit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # Fixed Adminer service
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  # Django Web Application
  web:
    build: .
    container_name: reserveit_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:mypassword123@db:5432/reserveit_db

  # # Next.js Frontend Application
  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: reserveit_frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   command: npm run dev
  #   depends_on:
  #     - web

volumes:
  postgres_data: